.TH "PaymentController" 3 "Dc Mai 15 2019" "Version 1.0" "Univeylandia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaymentController
.SH SYNOPSIS
.br
.PP
.PP
Hereta de \fBController\fP\&.
.SS "Mètodes públics"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBindex\fP ()"
.br
.ti -1c
.RI "\fBpayWithpaypal\fP (Request $request)"
.br
.ti -1c
.RI "\fBgetPaymentStatus\fP ()"
.br
.in -1c
.SH "Documentació del Constructor i el Destructor"
.PP 
.SS "__construct ()"
Create a new controller instance\&.
.PP
\fBRetorna:\fP
.RS 4
void 
.RE
.PP
PayPal api context 
.SH "Documentació de les Funcions Membre"
.PP 
.SS "getPaymentStatus ()"
Execute the payment 
.SS "payWithpaypal (Request $request)"
redirect to paypal 

.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Univeylandia a partir del codi font\&.
