.TH "ZonesController" 3 "Dc Mai 15 2019" "Version 1.0" "Univeylandia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZonesController
.SH SYNOPSIS
.br
.PP
.PP
Hereta de \fBController\fP\&.
.SS "Mètodes públics"

.in +1c
.ti -1c
.RI "\fBindex\fP ()"
.br
.ti -1c
.RI "\fBcreate\fP ()"
.br
.ti -1c
.RI "\fBstore\fP (Request $request)"
.br
.ti -1c
.RI "\fBshow\fP ($id)"
.br
.ti -1c
.RI "\fBedit\fP ($id)"
.br
.ti -1c
.RI "\fBupdate\fP (Request $request, $id)"
.br
.ti -1c
.RI "\fBdestroy\fP ($id)"
.br
.in -1c
.SH "Documentació de les Funcions Membre"
.PP 
.SS "create ()"
Show the form for creating a new resource\&.
.PP
\fBRetorna:\fP
.RS 4
/Illuminate/Http/Response 
.RE
.PP

.SS "destroy ( $id)"
Remove the specified resource from storage\&.
.PP
\fBParàmetres:\fP
.RS 4
\fI$id\fP 
.RE
.PP
\fBRetorna:\fP
.RS 4
/Illuminate/Http/Response 
.RE
.PP

.SS "edit ( $id)"
Show the form for editing the specified resource\&.
.PP
\fBParàmetres:\fP
.RS 4
\fI$id\fP 
.RE
.PP
\fBRetorna:\fP
.RS 4
/Illuminate/Http/Response 
.RE
.PP

.SS "index ()"
Display a listing of the resource\&.
.PP
\fBRetorna:\fP
.RS 4
/Illuminate/Http/Response 
.RE
.PP

.SS "show ( $id)"
Display the specified resource\&.
.PP
\fBParàmetres:\fP
.RS 4
\fI$id\fP 
.RE
.PP
\fBRetorna:\fP
.RS 4
/Illuminate/Http/Response 
.RE
.PP

.SS "store (Request $request)"
Store a newly created resource in storage\&.
.PP
\fBParàmetres:\fP
.RS 4
\fI$request\fP 
.RE
.PP
\fBRetorna:\fP
.RS 4
/Illuminate/Http/Response 
.RE
.PP

.SS "update (Request $request,  $id)"
Update the specified resource in storage\&.
.PP
\fBParàmetres:\fP
.RS 4
\fI$request\fP 
.br
\fI$id\fP 
.RE
.PP
\fBRetorna:\fP
.RS 4
/Illuminate/Http/Response 
.RE
.PP


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Univeylandia a partir del codi font\&.
