.TH "ServeisController" 3 "Dc Mai 15 2019" "Version 1.0" "Univeylandia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServeisController
.SH SYNOPSIS
.br
.PP
.PP
Hereta de \fBController\fP\&.
.SS "Mètodes públics"

.in +1c
.ti -1c
.RI "\fBindex\fP ()"
.br
.ti -1c
.RI "\fBcreate\fP ()"
.br
.ti -1c
.RI "\fBstore\fP (Request $request)"
.br
.ti -1c
.RI "\fBshow\fP ($id)"
.br
.ti -1c
.RI "\fBedit\fP ($id)"
.br
.ti -1c
.RI "\fBupdate\fP (Request $request, $id)"
.br
.ti -1c
.RI "\fBdestroy\fP ($id)"
.br
.in -1c
.SH "Documentació de les Funcions Membre"
.PP 
.SS "create ()"
Acció que s'encarrega de retornar la vista per a crear un servei\&.
.PP
\fBRetorna:\fP
.RS 4
/Illuminate/Http/Response 
.RE
.PP

.SS "destroy ( $id)"
Acció que s'encarrega de canviar l'estat del servei a finalitzat
.PP
\fBParàmetres:\fP
.RS 4
\fI$id\fP 
.RE
.PP
\fBRetorna:\fP
.RS 4
/Illuminate/Http/Response 
.RE
.PP

.SS "edit ( $id)"
Acció que s'encarrega de mostrar les dades del servei per a modificarles\&.
.PP
\fBParàmetres:\fP
.RS 4
\fI$id\fP 
.RE
.PP
\fBRetorna:\fP
.RS 4
/Illuminate/Http/Response 
.RE
.PP

.SS "index ()"
Acció que s'encarrega de llistar els serveis del parc\&.
.PP
\fBRetorna:\fP
.RS 4
/Illuminate/Http/Response 
.RE
.PP

.SS "show ( $id)"
Display the specified resource\&.
.PP
\fBParàmetres:\fP
.RS 4
\fI$id\fP 
.RE
.PP
\fBRetorna:\fP
.RS 4
/Illuminate/Http/Response 
.RE
.PP

.SS "store (Request $request)"
Acció que guarda el servei creat a la base de dades\&.
.PP
\fBParàmetres:\fP
.RS 4
\fI$request\fP 
.RE
.PP
\fBRetorna:\fP
.RS 4
/Illuminate/Http/Response 
.RE
.PP

.SS "update (Request $request,  $id)"
Acció que s'encarrega d'actualitzar les dades a la base de dades\&.
.PP
\fBParàmetres:\fP
.RS 4
\fI$request\fP 
.br
\fI$id\fP 
.RE
.PP
\fBRetorna:\fP
.RS 4
/Illuminate/Http/Response 
.RE
.PP


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Univeylandia a partir del codi font\&.
