.TH "Controller" 3 "Dc Mai 15 2019" "Version 1.0" "Univeylandia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controller
.SH SYNOPSIS
.br
.PP
.PP
Hereta de BaseController\&.
.PP
Heretat per \fBAssignEmpZonaController\fP, \fBAssignEmpZonaController\fP, \fBAtraccionsController\fP, \fBClientsController\fP, \fBContacteController\fP, \fBDownloadsController\fP, \fBEmpleatsController\fP, \fBgestioProductes\fP, \fBGestioServeisController\fP, \fBGrafiquesController\fP, \fBHomeController\fP, \fBImageController\fP, \fBIncidenciesController\fP, \fBNoticiesController\fP, \fBNotificationsController\fP, \fBPaymentController\fP, \fBPerfilController\fP, \fBPromocionsController\fP, \fBServeisController\fP, \fBTendaController\fP, \fBVentesController\fP i \fBZonesController\fP\&.

.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Univeylandia a partir del codi font\&.
