.TH "App\Http\Controllers" 3 "Tue May 14 2019" "Version 1.0" "Univeylandia - Controllers doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Http\Controllers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAssignEmpZonaController\fP"
.br
.ti -1c
.RI "class \fBAtraccionsController\fP"
.br
.ti -1c
.RI "class \fBClientsController\fP"
.br
.ti -1c
.RI "class \fBContacteController\fP"
.br
.ti -1c
.RI "class \fBController\fP"
.br
.ti -1c
.RI "class \fBDownloadsController\fP"
.br
.ti -1c
.RI "class \fBEmpleatsController\fP"
.br
.ti -1c
.RI "class \fBgestioProductes\fP"
.br
.ti -1c
.RI "class \fBGestioServeisController\fP"
.br
.ti -1c
.RI "class \fBGrafiquesController\fP"
.br
.ti -1c
.RI "class \fBHomeController\fP"
.br
.ti -1c
.RI "class \fBImageController\fP"
.br
.ti -1c
.RI "class \fBIncidenciesController\fP"
.br
.ti -1c
.RI "class \fBNoticiesController\fP"
.br
.ti -1c
.RI "class \fBNotificationsController\fP"
.br
.ti -1c
.RI "class \fBPaymentController\fP"
.br
.ti -1c
.RI "class \fBPerfilController\fP"
.br
.ti -1c
.RI "class \fBPromocionsController\fP"
.br
.ti -1c
.RI "class \fBServeisController\fP"
.br
.ti -1c
.RI "class \fBTendaController\fP"
.br
.ti -1c
.RI "class \fBVentesController\fP"
.br
.ti -1c
.RI "class \fBZonesController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Univeylandia - Controllers doc from the source code\&.
